module.exports = {
    ERROR_WRONG_USER: 'ERROR_WRONG_USER',
    ERROR_USER_IS_ALREADY_A_MANAGER: 'ERROR_USER_IS_ALREADY_A_MANAGER',
    ERROR_USER_STILL_MANAGING_EVENTS: 'ERROR_USER_STILL_MANAGING_EVENTS',
    ERROR_USER_DOES_NOT_MEET_REQUIRED_ROLES: 'ERROR_USER_DOES_NOT_MEET_REQUIRED_ROLES',
    ERROR_CAN_NOT_MODIFY_ROOT_USER: 'ERROR_CAN_NOT_MODIFY_ROOT_USER',
    ERROR_USER_CAN_NOT_BANN_IT_SELF: 'ERROR_USER_CAN_NOT_BANN_IT_SELF',
    ERROR_USERNAME_REQUIRED: 'ERROR_USERNAME_REQUIRED',
    ERROR_PASSWORD_REQUIRED: 'ERROR_PASSWORD_REQUIRED',
    ERROR_USERNAME_PASSWORD_INVALID: 'ERROR_USERNAME_PASSWORD_INVALID',
    ERROR_USER_IS_NOT_EVENT_OWNER: 'ERROR_USER_IS_NOT_EVENT_OWNER',
    ERROR_USER_BANNED: 'ERROR_USER_BANNED',
}